# Generated by Django 2.2.2 on 2019-06-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190619_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cosmetics',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='groceries',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
