# Generated by Django 2.2.2 on 2019-06-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190619_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cosmetics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='groceries',
        ),
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.CharField(default='ITEM', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='PRICE', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default='QUANTITY', max_length=200),
        ),
    ]
