# Generated by Django 2.2.2 on 2019-07-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visualizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='ITEM', max_length=200)),
                ('quantity', models.CharField(default='QUANTITY', max_length=200)),
                ('price', models.CharField(default='PRICE', max_length=200)),
            ],
        ),
    ]
