# Generated by Django 2.2.2 on 2019-07-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualizations',
            name='price',
        ),
    ]
