# Generated by Django 2.2.2 on 2019-07-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_remove_visualizations_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualizations',
            name='item',
        ),
        migrations.RemoveField(
            model_name='visualizations',
            name='quantity',
        ),
        migrations.AddField(
            model_name='visualizations',
            name='antecedent_support',
            field=models.CharField(default='ANTECEDENT_SUPPORT', max_length=200),
        ),
        migrations.AddField(
            model_name='visualizations',
            name='antecedents',
            field=models.CharField(default='ANTECEDENTS', max_length=200),
        ),
        migrations.AddField(
            model_name='visualizations',
            name='confidence',
            field=models.CharField(default='CONFIDENCE', max_length=200),
        ),
        migrations.AddField(
            model_name='visualizations',
            name='consequent_support',
            field=models.CharField(default='CONSEQUENT_SUPPORT', max_length=200),
        ),
        migrations.AddField(
            model_name='visualizations',
            name='consequents',
            field=models.CharField(default='CONSEQUENTS', max_length=200),
        ),
        migrations.AddField(
            model_name='visualizations',
            name='conviction',
            field=models.CharField(default='CONVICTION', max_length=200),
        ),
        migrations.AddField(
            model_name='visualizations',
            name='leverage',
            field=models.CharField(default='LEVERAGE', max_length=200),
        ),
        migrations.AddField(
            model_name='visualizations',
            name='lift',
            field=models.CharField(default='LIFT', max_length=200),
        ),
        migrations.AddField(
            model_name='visualizations',
            name='support',
            field=models.CharField(default='SUPPORT', max_length=200),
        ),
    ]
