# Generated by Django 2.2.2 on 2019-07-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_auto_20190725_2045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visualizations',
            new_name='Visualization',
        ),
    ]
